<?php

namespace Telanflow\Binlog\Constants;

class CharsetConst
{
    const ARMSCII8_BIN             = 64;
    const ARMSCII8_GENERAL_CI      = 32;
    const ASCII_BIN                = 65;
    const ASCII_GENERAL_CI         = 11;
    const BIG5_BIN                 = 84;
    const BIG5_CHINESE_CI          = 1;
    const BINARY                   = 63;
    const CP1250_BIN               = 66;
    const CP1250_CROATIAN_CI       = 44;
    const CP1250_CZECH_CS          = 34;
    const CP1250_GENERAL_CI        = 26;
    const CP1250_POLISH_CI         = 99;
    const CP1251_BIN               = 50;
    const CP1251_BULGARIAN_CI      = 14;
    const CP1251_GENERAL_CI        = 51;
    const CP1251_GENERAL_CS        = 52;
    const CP1251_UKRAINIAN_CI      = 23;
    const CP1256_BIN               = 67;
    const CP1256_GENERAL_CI        = 57;
    const CP1257_BIN               = 58;
    const CP1257_GENERAL_CI        = 59;
    const CP1257_LITHUANIAN_CI     = 29;
    const CP850_BIN                = 80;
    const CP850_GENERAL_CI         = 4;
    const CP852_BIN                = 81;
    const CP852_GENERAL_CI         = 40;
    const CP866_BIN                = 68;
    const CP866_GENERAL_CI         = 36;
    const CP932_BIN                = 96;
    const CP932_JAPANESE_CI        = 95;
    const DEC8_BIN                 = 69;
    const DEC8_SWEDISH_CI          = 3;
    const EUCJPMS_BIN              = 98;
    const EUCJPMS_JAPANESE_CI      = 97;
    const EUCKR_BIN                = 85;
    const EUCKR_KOREAN_CI          = 19;
    const GB2312_BIN               = 86;
    const GB2312_CHINESE_CI        = 24;
    const GBK_BIN                  = 87;
    const GBK_CHINESE_CI           = 28;
    const GEOSTD8_BIN              = 93;
    const GEOSTD8_GENERAL_CI       = 92;
    const GREEK_BIN                = 70;
    const GREEK_GENERAL_CI         = 25;
    const HEBREW_BIN               = 71;
    const HEBREW_GENERAL_CI        = 16;
    const HP8_BIN                  = 72;
    const HP8_ENGLISH_CI           = 6;
    const KEYBCS2_BIN              = 73;
    const KEYBCS2_GENERAL_CI       = 37;
    const KOI8R_BIN                = 74;
    const KOI8R_GENERAL_CI         = 7;
    const KOI8U_BIN                = 75;
    const KOI8U_GENERAL_CI         = 22;
    const LATIN1_BIN               = 47;
    const LATIN1_DANISH_CI         = 15;
    const LATIN1_GENERAL_CI        = 48;
    const LATIN1_GENERAL_CS        = 49;
    const LATIN1_GERMAN1_CI        = 5;
    const LATIN1_GERMAN2_CI        = 31;
    const LATIN1_SPANISH_CI        = 94;
    const LATIN1_SWEDISH_CI        = 8;
    const LATIN2_BIN               = 77;
    const LATIN2_CROATIAN_CI       = 27;
    const LATIN2_CZECH_CS          = 2;
    const LATIN2_GENERAL_CI        = 9;
    const LATIN2_HUNGARIAN_CI      = 21;
    const LATIN5_BIN               = 78;
    const LATIN5_TURKISH_CI        = 30;
    const LATIN7_BIN               = 79;
    const LATIN7_ESTONIAN_CS       = 20;
    const LATIN7_GENERAL_CI        = 41;
    const LATIN7_GENERAL_CS        = 42;
    const MACCE_BIN                = 43;
    const MACCE_GENERAL_CI         = 38;
    const MACROMAN_BIN             = 53;
    const MACROMAN_GENERAL_CI      = 39;
    const SJIS_BIN                 = 88;
    const SJIS_JAPANESE_CI         = 13;
    const SWE7_BIN                 = 82;
    const SWE7_SWEDISH_CI          = 10;
    const TIS620_BIN               = 89;
    const TIS620_THAI_CI           = 18;
    const UCS2_BIN                 = 90;
    const UCS2_CZECH_CI            = 138;
    const UCS2_DANISH_CI           = 139;
    const UCS2_ESPERANTO_CI        = 145;
    const UCS2_ESTONIAN_CI         = 134;
    const UCS2_GENERAL_CI          = 35;
    const UCS2_GENERAL_MYSQL500_CI = 159;
    const UCS2_HUNGARIAN_CI        = 146;
    const UCS2_ICELANDIC_CI        = 129;
    const UCS2_LATVIAN_CI          = 130;
    const UCS2_LITHUANIAN_CI       = 140;
    const UCS2_PERSIAN_CI          = 144;
    const UCS2_POLISH_CI           = 133;
    const UCS2_ROMANIAN_CI         = 131;
    const UCS2_ROMAN_CI            = 143;
    const UCS2_SINHALA_CI          = 147;
    const UCS2_SLOVAK_CI           = 141;
    const UCS2_SLOVENIAN_CI        = 132;
    const UCS2_SPANISH2_CI         = 142;
    const UCS2_SPANISH_CI          = 135;
    const UCS2_SWEDISH_CI          = 136;
    const UCS2_TURKISH_CI          = 137;
    const UCS2_UNICODE_CI          = 128;
    const UJIS_BIN                 = 91;
    const UJIS_JAPANESE_CI         = 12;
    const UTF16_BIN                = 55;
    const UTF16_CZECH_CI           = 111;
    const UTF16_DANISH_CI          = 112;
    const UTF16_ESPERANTO_CI       = 118;
    const UTF16_ESTONIAN_CI        = 107;
    const UTF16_GENERAL_CI         = 54;
    const UTF16_HUNGARIAN_CI       = 119;
    const UTF16_ICELANDIC_CI       = 102;
    const UTF16_LATVIAN_CI         = 103;
    const UTF16_LITHUANIAN_CI      = 113;
    const UTF16_PERSIAN_CI         = 117;
    const UTF16_POLISH_CI          = 106;
    const UTF16_ROMANIAN_CI        = 104;
    const UTF16_ROMAN_CI           = 116;
    const UTF16_SINHALA_CI         = 120;
    const UTF16_SLOVAK_CI          = 114;
    const UTF16_SLOVENIAN_CI       = 105;
    const UTF16_SPANISH2_CI        = 115;
    const UTF16_SPANISH_CI         = 108;
    const UTF16_SWEDISH_CI         = 109;
    const UTF16_TURKISH_CI         = 110;
    const UTF16_UNICODE_CI         = 101;
    const UTF32_BIN                = 61;
    const UTF32_CZECH_CI           = 179;
    const UTF32_DANISH_CI          = 171;
    const UTF32_ESPERANTO_CI       = 177;
    const UTF32_ESTONIAN_CI        = 166;
    const UTF32_GENERAL_CI         = 60;
    const UTF32_HUNGARIAN_CI       = 178;
    const UTF32_ICELANDIC_CI       = 161;
    const UTF32_LATVIAN_CI         = 162;
    const UTF32_LITHUANIAN_CI      = 172;
    const UTF32_PERSIAN_CI         = 176;
    const UTF32_POLISH_CI          = 165;
    const UTF32_ROMANIAN_CI        = 163;
    const UTF32_ROMAN_CI           = 175;
    const UTF32_SINHALA_CI         = 179;
    const UTF32_SLOVAK_CI          = 173;
    const UTF32_SLOVENIAN_CI       = 164;
    const UTF32_SPANISH2_CI        = 174;
    const UTF32_SPANISH_CI         = 167;
    const UTF32_SWEDISH_CI         = 168;
    const UTF32_TURKISH_CI         = 169;
    const UTF32_UNICODE_CI         = 160;
    const UTF8MB4_BIN              = 46;
    const UTF8MB4_CZECH_CI         = 234;
    const UTF8MB4_DANISH_CI        = 235;
    const UTF8MB4_ESPERANTO_CI     = 241;
    const UTF8MB4_ESTONIAN_CI      = 230;
    const UTF8MB4_GENERAL_CI       = 45;
    const UTF8MB4_HUNGARIAN_CI     = 242;
    const UTF8MB4_ICELANDIC_CI     = 225;
    const UTF8MB4_LATVIAN_CI       = 226;
    const UTF8MB4_LITHUANIAN_CI    = 236;
    const UTF8MB4_PERSIAN_CI       = 240;
    const UTF8MB4_POLISH_CI        = 229;
    const UTF8MB4_ROMANIAN_CI      = 227;
    const UTF8MB4_ROMAN_CI         = 239;
    const UTF8MB4_SINHALA_CI       = 243;
    const UTF8MB4_SLOVAK_CI        = 237;
    const UTF8MB4_SLOVENIAN_CI     = 228;
    const UTF8MB4_SPANISH2_CI      = 238;
    const UTF8MB4_SPANISH_CI       = 231;
    const UTF8MB4_SWEDISH_CI       = 232;
    const UTF8MB4_TURKISH_CI       = 233;
    const UTF8MB4_UNICODE_CI       = 224;
    const UTF8_BIN                 = 83;
    const UTF8_CZECH_CI            = 202;
    const UTF8_DANISH_CI           = 203;
    const UTF8_ESPERANTO_CI        = 209;
    const UTF8_ESTONIAN_CI         = 198;
    const UTF8_GENERAL_CI          = 33;
    const UTF8_GENERAL_MYSQL500_CI = 223;
    const UTF8_HUNGARIAN_CI        = 210;
    const UTF8_ICELANDIC_CI        = 193;
    const UTF8_LATVIAN_CI          = 194;
    const UTF8_LITHUANIAN_CI       = 204;
    const UTF8_PERSIAN_CI          = 208;
    const UTF8_POLISH_CI           = 197;
    const UTF8_ROMANIAN_CI         = 195;
    const UTF8_ROMAN_CI            = 207;
    const UTF8_SINHALA_CI          = 211;
    const UTF8_SLOVAK_CI           = 205;
    const UTF8_SLOVENIAN_CI        = 196;
    const UTF8_SPANISH2_CI         = 206;
    const UTF8_SPANISH_CI          = 199;
    const UTF8_SWEDISH_CI          = 200;
    const UTF8_TURKISH_CI          = 201;
    const UTF8_UNICODE_CI          = 192;

    public static $map = [
        self::ARMSCII8_BIN              => 'armscii8_bin',
        self::ARMSCII8_GENERAL_CI       => 'armscii8_general_ci',
        self::ASCII_BIN                 => 'ascii_bin',
        self::ASCII_GENERAL_CI          => 'ascii_general_ci',
        self::BIG5_BIN                  => 'big5_bin',
        self::BIG5_CHINESE_CI           => 'big5_chinese_ci',
        self::BINARY                    => 'binary',
        self::CP1250_BIN                => 'cp1250_bin',
        self::CP1250_CROATIAN_CI        => 'cp1250_croatian_ci',
        self::CP1250_CZECH_CS           => 'cp1250_czech_cs',
        self::CP1250_GENERAL_CI         => 'cp1250_general_ci',
        self::CP1250_POLISH_CI          => 'cp1250_polish_ci',
        self::CP1251_BIN                => 'cp1251_bin',
        self::CP1251_BULGARIAN_CI       => 'cp1251_bulgarian_ci',
        self::CP1251_GENERAL_CI         => 'cp1251_general_ci',
        self::CP1251_GENERAL_CS         => 'cp1251_general_cs',
        self::CP1251_UKRAINIAN_CI       => 'cp1251_ukrainian_ci',
        self::CP1256_BIN                => 'cp1256_bin',
        self::CP1256_GENERAL_CI         => 'cp1256_general_ci',
        self::CP1257_BIN                => 'cp1257_bin',
        self::CP1257_GENERAL_CI         => 'cp1257_general_ci',
        self::CP1257_LITHUANIAN_CI      => 'cp1257_lithuanian_ci',
        self::CP850_BIN                 => 'cp850_bin',
        self::CP850_GENERAL_CI          => 'cp850_general_ci',
        self::CP852_BIN                 => 'cp852_bin',
        self::CP852_GENERAL_CI          => 'cp852_general_ci',
        self::CP866_BIN                 => 'cp866_bin',
        self::CP866_GENERAL_CI          => 'cp866_general_ci',
        self::CP932_BIN                 => 'cp932_bin',
        self::CP932_JAPANESE_CI         => 'cp932_japanese_ci',
        self::DEC8_BIN                  => 'dec8_bin',
        self::DEC8_SWEDISH_CI           => 'dec8_swedish_ci',
        self::EUCJPMS_BIN               => 'eucjpms_bin',
        self::EUCJPMS_JAPANESE_CI       => 'eucjpms_japanese_ci',
        self::EUCKR_BIN                 => 'euckr_bin',
        self::EUCKR_KOREAN_CI           => 'euckr_korean_ci',
        self::GB2312_BIN                => 'gb2312_bin',
        self::GB2312_CHINESE_CI         => 'gb2312_chinese_ci',
        self::GBK_BIN                   => 'gbk_bin',
        self::GBK_CHINESE_CI            => 'gbk_chinese_ci',
        self::GEOSTD8_BIN               => 'geostd8_bin',
        self::GEOSTD8_GENERAL_CI        => 'geostd8_general_ci',
        self::GREEK_BIN                 => 'greek_bin',
        self::GREEK_GENERAL_CI          => 'greek_general_ci',
        self::HEBREW_BIN                => 'hebrew_bin',
        self::HEBREW_GENERAL_CI         => 'hebrew_general_ci',
        self::HP8_BIN                   => 'hp8_bin',
        self::HP8_ENGLISH_CI            => 'hp8_english_ci',
        self::KEYBCS2_BIN               => 'keybcs2_bin',
        self::KEYBCS2_GENERAL_CI        => 'keybcs2_general_ci',
        self::KOI8R_BIN                 => 'koi8r_bin',
        self::KOI8R_GENERAL_CI          => 'koi8r_general_ci',
        self::KOI8U_BIN                 => 'koi8u_bin',
        self::KOI8U_GENERAL_CI          => 'koi8u_general_ci',
        self::LATIN1_BIN                => 'latin1_bin',
        self::LATIN1_DANISH_CI          => 'latin1_danish_ci',
        self::LATIN1_GENERAL_CI         => 'latin1_general_ci',
        self::LATIN1_GENERAL_CS         => 'latin1_general_cs',
        self::LATIN1_GERMAN1_CI         => 'latin1_german1_ci',
        self::LATIN1_GERMAN2_CI         => 'latin1_german2_ci',
        self::LATIN1_SPANISH_CI         => 'latin1_spanish_ci',
        self::LATIN1_SWEDISH_CI         => 'latin1_swedish_ci',
        self::LATIN2_BIN                => 'latin2_bin',
        self::LATIN2_CROATIAN_CI        => 'latin2_croatian_ci',
        self::LATIN2_CZECH_CS           => 'latin2_czech_cs',
        self::LATIN2_GENERAL_CI         => 'latin2_general_ci',
        self::LATIN2_HUNGARIAN_CI       => 'latin2_hungarian_ci',
        self::LATIN5_BIN                => 'latin5_bin',
        self::LATIN5_TURKISH_CI         => 'latin5_turkish_ci',
        self::LATIN7_BIN                => 'latin7_bin',
        self::LATIN7_ESTONIAN_CS        => 'latin7_estonian_cs',
        self::LATIN7_GENERAL_CI         => 'latin7_general_ci',
        self::LATIN7_GENERAL_CS         => 'latin7_general_cs',
        self::MACCE_BIN                 => 'macce_bin',
        self::MACCE_GENERAL_CI          => 'macce_general_ci',
        self::MACROMAN_BIN              => 'macroman_bin',
        self::MACROMAN_GENERAL_CI       => 'macroman_general_ci',
        self::SJIS_BIN                  => 'sjis_bin',
        self::SJIS_JAPANESE_CI          => 'sjis_japanese_ci',
        self::SWE7_BIN                  => 'swe7_bin',
        self::SWE7_SWEDISH_CI           => 'swe7_swedish_ci',
        self::TIS620_BIN                => 'tis620_bin',
        self::TIS620_THAI_CI            => 'tis620_thai_ci',
        self::UCS2_BIN                  => 'ucs2_bin',
        self::UCS2_CZECH_CI             => 'ucs2_czech_ci',
        self::UCS2_DANISH_CI            => 'ucs2_danish_ci',
        self::UCS2_ESPERANTO_CI         => 'ucs2_esperanto_ci',
        self::UCS2_ESTONIAN_CI          => 'ucs2_estonian_ci',
        self::UCS2_GENERAL_CI           => 'ucs2_general_ci',
        self::UCS2_GENERAL_MYSQL500_CI  => 'ucs2_general_mysql500_ci',
        self::UCS2_HUNGARIAN_CI         => 'ucs2_hungarian_ci',
        self::UCS2_ICELANDIC_CI         => 'ucs2_icelandic_ci',
        self::UCS2_LATVIAN_CI           => 'ucs2_latvian_ci',
        self::UCS2_LITHUANIAN_CI        => 'ucs2_lithuanian_ci',
        self::UCS2_PERSIAN_CI           => 'ucs2_persian_ci',
        self::UCS2_POLISH_CI            => 'ucs2_polish_ci',
        self::UCS2_ROMANIAN_CI          => 'ucs2_romanian_ci',
        self::UCS2_ROMAN_CI             => 'ucs2_roman_ci',
        self::UCS2_SINHALA_CI           => 'ucs2_sinhala_ci',
        self::UCS2_SLOVAK_CI            => 'ucs2_slovak_ci',
        self::UCS2_SLOVENIAN_CI         => 'ucs2_slovenian_ci',
        self::UCS2_SPANISH2_CI          => 'ucs2_spanish2_ci',
        self::UCS2_SPANISH_CI           => 'ucs2_spanish_ci',
        self::UCS2_SWEDISH_CI           => 'ucs2_swedish_ci',
        self::UCS2_TURKISH_CI           => 'ucs2_turkish_ci',
        self::UCS2_UNICODE_CI           => 'ucs2_unicode_ci',
        self::UJIS_BIN                  => 'ujis_bin',
        self::UJIS_JAPANESE_CI          => 'ujis_japanese_ci',
        self::UTF16_BIN                 => 'utf16_bin',
        self::UTF16_CZECH_CI            => 'utf16_czech_ci',
        self::UTF16_DANISH_CI           => 'utf16_danish_ci',
        self::UTF16_ESPERANTO_CI        => 'utf16_esperanto_ci',
        self::UTF16_ESTONIAN_CI         => 'utf16_estonian_ci',
        self::UTF16_GENERAL_CI          => 'utf16_general_ci',
        self::UTF16_HUNGARIAN_CI        => 'utf16_hungarian_ci',
        self::UTF16_ICELANDIC_CI        => 'utf16_icelandic_ci',
        self::UTF16_LATVIAN_CI          => 'utf16_latvian_ci',
        self::UTF16_LITHUANIAN_CI       => 'utf16_lithuanian_ci',
        self::UTF16_PERSIAN_CI          => 'utf16_persian_ci',
        self::UTF16_POLISH_CI           => 'utf16_polish_ci',
        self::UTF16_ROMANIAN_CI         => 'utf16_romanian_ci',
        self::UTF16_ROMAN_CI            => 'utf16_roman_ci',
        self::UTF16_SINHALA_CI          => 'utf16_sinhala_ci',
        self::UTF16_SLOVAK_CI           => 'utf16_slovak_ci',
        self::UTF16_SLOVENIAN_CI        => 'utf16_slovenian_ci',
        self::UTF16_SPANISH2_CI         => 'utf16_spanish2_ci',
        self::UTF16_SPANISH_CI          => 'utf16_spanish_ci',
        self::UTF16_SWEDISH_CI          => 'utf16_swedish_ci',
        self::UTF16_TURKISH_CI          => 'utf16_turkish_ci',
        self::UTF16_UNICODE_CI          => 'utf16_unicode_ci',
        self::UTF32_BIN                 => 'utf32_bin',
        self::UTF32_CZECH_CI            => 'utf32_czech_ci',
        self::UTF32_DANISH_CI           => 'utf32_danish_ci',
        self::UTF32_ESPERANTO_CI        => 'utf32_esperanto_ci',
        self::UTF32_ESTONIAN_CI         => 'utf32_estonian_ci',
        self::UTF32_GENERAL_CI          => 'utf32_general_ci',
        self::UTF32_HUNGARIAN_CI        => 'utf32_hungarian_ci',
        self::UTF32_ICELANDIC_CI        => 'utf32_icelandic_ci',
        self::UTF32_LATVIAN_CI          => 'utf32_latvian_ci',
        self::UTF32_LITHUANIAN_CI       => 'utf32_lithuanian_ci',
        self::UTF32_PERSIAN_CI          => 'utf32_persian_ci',
        self::UTF32_POLISH_CI           => 'utf32_polish_ci',
        self::UTF32_ROMANIAN_CI         => 'utf32_romanian_ci',
        self::UTF32_ROMAN_CI            => 'utf32_roman_ci',
        self::UTF32_SINHALA_CI          => 'utf32_sinhala_ci',
        self::UTF32_SLOVAK_CI           => 'utf32_slovak_ci',
        self::UTF32_SLOVENIAN_CI        => 'utf32_slovenian_ci',
        self::UTF32_SPANISH2_CI         => 'utf32_spanish2_ci',
        self::UTF32_SPANISH_CI          => 'utf32_spanish_ci',
        self::UTF32_SWEDISH_CI          => 'utf32_swedish_ci',
        self::UTF32_TURKISH_CI          => 'utf32_turkish_ci',
        self::UTF32_UNICODE_CI          => 'utf32_unicode_ci',
        self::UTF8MB4_BIN               => 'utf8mb4_bin',
        self::UTF8MB4_CZECH_CI          => 'utf8mb4_czech_ci',
        self::UTF8MB4_DANISH_CI         => 'utf8mb4_danish_ci',
        self::UTF8MB4_ESPERANTO_CI      => 'utf8mb4_esperanto_ci',
        self::UTF8MB4_ESTONIAN_CI       => 'utf8mb4_estonian_ci',
        self::UTF8MB4_GENERAL_CI        => 'utf8mb4_general_ci',
        self::UTF8MB4_HUNGARIAN_CI      => 'utf8mb4_hungarian_ci',
        self::UTF8MB4_ICELANDIC_CI      => 'utf8mb4_icelandic_ci',
        self::UTF8MB4_LATVIAN_CI        => 'utf8mb4_latvian_ci',
        self::UTF8MB4_LITHUANIAN_CI     => 'utf8mb4_lithuanian_ci',
        self::UTF8MB4_PERSIAN_CI        => 'utf8mb4_persian_ci',
        self::UTF8MB4_POLISH_CI         => 'utf8mb4_polish_ci',
        self::UTF8MB4_ROMANIAN_CI       => 'utf8mb4_romanian_ci',
        self::UTF8MB4_ROMAN_CI          => 'utf8mb4_roman_ci',
        self::UTF8MB4_SINHALA_CI        => 'utf8mb4_sinhala_ci',
        self::UTF8MB4_SLOVAK_CI         => 'utf8mb4_slovak_ci',
        self::UTF8MB4_SLOVENIAN_CI      => 'utf8mb4_slovenian_ci',
        self::UTF8MB4_SPANISH2_CI       => 'utf8mb4_spanish2_ci',
        self::UTF8MB4_SPANISH_CI        => 'utf8mb4_spanish_ci',
        self::UTF8MB4_SWEDISH_CI        => 'utf8mb4_swedish_ci',
        self::UTF8MB4_TURKISH_CI        => 'utf8mb4_turkish_ci',
        self::UTF8MB4_UNICODE_CI        => 'utf8mb4_unicode_ci',
        self::UTF8_BIN                  => 'utf8_bin',
        self::UTF8_CZECH_CI             => 'utf8_czech_ci',
        self::UTF8_DANISH_CI            => 'utf8_danish_ci',
        self::UTF8_ESPERANTO_CI         => 'utf8_esperanto_ci',
        self::UTF8_ESTONIAN_CI          => 'utf8_estonian_ci',
        self::UTF8_GENERAL_CI           => 'utf8_general_ci',
        self::UTF8_GENERAL_MYSQL500_CI  => 'utf8_general_mysql500_ci',
        self::UTF8_HUNGARIAN_CI         => 'utf8_hungarian_ci',
        self::UTF8_ICELANDIC_CI         => 'utf8_icelandic_ci',
        self::UTF8_LATVIAN_CI           => 'utf8_latvian_ci',
        self::UTF8_LITHUANIAN_CI        => 'utf8_lithuanian_ci',
        self::UTF8_PERSIAN_CI           => 'utf8_persian_ci',
        self::UTF8_POLISH_CI            => 'utf8_polish_ci',
        self::UTF8_ROMANIAN_CI          => 'utf8_romanian_ci',
        self::UTF8_ROMAN_CI             => 'utf8_roman_ci',
        self::UTF8_SINHALA_CI           => 'utf8_sinhala_ci',
        self::UTF8_SLOVAK_CI            => 'utf8_slovak_ci',
        self::UTF8_SLOVENIAN_CI         => 'utf8_slovenian_ci',
        self::UTF8_SPANISH2_CI          => 'utf8_spanish2_ci',
        self::UTF8_SPANISH_CI           => 'utf8_spanish_ci',
        self::UTF8_SWEDISH_CI           => 'utf8_swedish_ci',
        self::UTF8_TURKISH_CI           => 'utf8_turkish_ci',
        self::UTF8_UNICODE_CI           => 'utf8_unicode_ci',
    ];

}
